-- MySQL Script generated by MySQL Workbench
-- Tue Oct  6 13:26:32 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema moblex-db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema moblex-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `moblex-db` ;
USE `moblex-db` ;

-- -----------------------------------------------------
-- Table `moblex-db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moblex-db`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(10) NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  `wallet` FLOAT NULL,
  `created_at` DATE NULL,
  PRIMARY KEY (`idusers`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moblex-db`.`owned_houses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moblex-db`.`owned_houses` (
  `idhouses` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NOT NULL,
  `state` VARCHAR(45) NULL,
  `price_to_rent` FLOAT NOT NULL,
  `users_idusers` INT NOT NULL,
  `price_to_sell` FLOAT NULL,
  `avaiable_to_sell` TINYINT NOT NULL,
  PRIMARY KEY (`idhouses`, `users_idusers`),
  INDEX `fk_owned_houses_users1_idx` (`users_idusers` ASC),
  CONSTRAINT `fk_owned_houses_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `moblex-db`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moblex-db`.`rented_houses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moblex-db`.`rented_houses` (
  `idrented_houses` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NULL,
  `state` VARCHAR(45) NULL,
  `price_to_rent` FLOAT NOT NULL,
  `avaiable` TINYINT NULL,
  `users_idusers` INT NOT NULL,
  PRIMARY KEY (`idrented_houses`, `users_idusers`),
  INDEX `fk_rented_houses_users_idx` (`users_idusers` ASC),
  CONSTRAINT `fk_rented_houses_users`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `moblex-db`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moblex-db`.`images_rented_houses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moblex-db`.`images_rented_houses` (
  `idimages_rented_houses` INT NOT NULL AUTO_INCREMENT,
  `image_address` VARCHAR(300) NULL,
  `rented_houses_idrented_houses` INT NOT NULL,
  `rented_houses_users_idusers` INT NOT NULL,
  PRIMARY KEY (`idimages_rented_houses`, `rented_houses_idrented_houses`, `rented_houses_users_idusers`),
  INDEX `fk_images_rented_houses_rented_houses1_idx` (`rented_houses_idrented_houses` ASC, `rented_houses_users_idusers` ASC),
  CONSTRAINT `fk_images_rented_houses_rented_houses1`
    FOREIGN KEY (`rented_houses_idrented_houses` , `rented_houses_users_idusers`)
    REFERENCES `moblex-db`.`rented_houses` (`idrented_houses` , `users_idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moblex-db`.`days_rented`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moblex-db`.`days_rented` (
  `iddays_rented` INT NOT NULL AUTO_INCREMENT,
  `initial_date_rented` DATE NULL,
  `end_date_rented` DATE NULL,
  `rented_houses_idrented_houses` INT NOT NULL,
  `rented_houses_users_idusers` INT NOT NULL,
  PRIMARY KEY (`iddays_rented`, `rented_houses_idrented_houses`, `rented_houses_users_idusers`),
  INDEX `fk_days_rented_rented_houses1_idx` (`rented_houses_idrented_houses` ASC, `rented_houses_users_idusers` ASC),
  CONSTRAINT `fk_days_rented_rented_houses1`
    FOREIGN KEY (`rented_houses_idrented_houses` , `rented_houses_users_idusers`)
    REFERENCES `moblex-db`.`rented_houses` (`idrented_houses` , `users_idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moblex-db`.`images_owned_houses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moblex-db`.`images_owned_houses` (
  `idimages_owned_houses` INT NOT NULL AUTO_INCREMENT,
  `image_address` VARCHAR(300) NULL,
  `owned_houses_idhouses` INT NOT NULL,
  `owned_houses_users_idusers` INT NOT NULL,
  PRIMARY KEY (`idimages_owned_houses`, `owned_houses_idhouses`, `owned_houses_users_idusers`),
  INDEX `fk_images_owned_houses_owned_houses1_idx` (`owned_houses_idhouses` ASC, `owned_houses_users_idusers` ASC),
  CONSTRAINT `fk_images_owned_houses_owned_houses1`
    FOREIGN KEY (`owned_houses_idhouses` , `owned_houses_users_idusers`)
    REFERENCES `moblex-db`.`owned_houses` (`idhouses` , `users_idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
